export var ENUM_OVERLAY_TYPE;
(function (ENUM_OVERLAY_TYPE) {
    ENUM_OVERLAY_TYPE["INPUT"] = "INPUT";
    ENUM_OVERLAY_TYPE["IMG_BLOCK"] = "IMG_BLOCK";
    ENUM_OVERLAY_TYPE["CHECKBOX"] = "CHECKBOX";
    ENUM_OVERLAY_TYPE["DATE_INPUT"] = "DATE_INPUT";
})(ENUM_OVERLAY_TYPE || (ENUM_OVERLAY_TYPE = {}));
export var ENUM_ORIGIN_TYPE;
(function (ENUM_ORIGIN_TYPE) {
    ENUM_ORIGIN_TYPE["LEFT_TOP"] = "LEFT_TOP";
    ENUM_ORIGIN_TYPE["LEFT_BOTTOM"] = "LEFT_BOTTOM";
    ENUM_ORIGIN_TYPE["CENTER"] = "CENTER";
})(ENUM_ORIGIN_TYPE || (ENUM_ORIGIN_TYPE = {}));
/**
 * 漂浮物状态
 * INPUT 可以进行输入
 * EDITING 编辑状态
 * FREE 自由签
 */
export var ENUM_OVERLAY_STATUS;
(function (ENUM_OVERLAY_STATUS) {
    ENUM_OVERLAY_STATUS["INPUT"] = "INPUT";
    ENUM_OVERLAY_STATUS["EDITING"] = "EDITING";
    ENUM_OVERLAY_STATUS["FREE"] = "FREE";
})(ENUM_OVERLAY_STATUS || (ENUM_OVERLAY_STATUS = {}));
//# sourceMappingURL=interface.js.map